#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';
require_once(__DIR__ . '/config/config.php');

use Fipe\Command\DefaultCommand;
use Fipe\Command\ExtrairVeiculoCommand;
use Fipe\Command\CsvCommand;
use Symfony\Component\Console\Application;
use Fipe\Database;

$db = new Fipe\Database($db['host'], $db['dbname'], $db['user'], $db['pass']);

$application = new Application();

$defaultCommand = new DefaultCommand;
$application->add($defaultCommand);
$application->setDefaultCommand($defaultCommand->getName());

$extVeiCommand = new ExtrairVeiculoCommand;
$extVeiCommand->setDb($db);
$application->add($extVeiCommand);

$csvCommand = new CsvCommand;
$csvCommand->setDb($db);
$application->add($csvCommand);

$application->run();